# Generated by Django 2.2.6 on 2019-10-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=500)),
                ('receiver', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
